service: hello-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-3

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

functions:
  hello:
    handler: src/index.hello
    events:
      - http:
          path: /
          method: get
